import "server-only";

import { adminDb } from "./firebase-admin";

export const defaultSiteContent = {
  homeHeroImageUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=2200&q=90",
  rentalHeroImageUrl: "/images/hero-sedan.png",
  topLine: "Karaman'da güvenilir çözüm ortağınız",
  brandSubtitle: "İNŞAAT · EMLAK · RENT A CAR",
  navHome: "Ana Sayfa",
  navConstruction: "İnşaat",
  navRealEstate: "Emlak",
  navRental: "Rent A Car",
  navAbout: "Hakkımızda",
  navContact: "İletişim",
  footerDescription: "İnşaat, emlak ve araç kiralamada güvenilir hizmet.",
  footerAddress: "Rauf Denktaş Mah. 2. İstasyon Cad. No: 39/A, Karaman",
  footerCopyright: "© 2026 Servet İnşaat Emlak Rent A Car. Tüm hakları saklıdır.",
  homeHeroEyebrow: "KARAMAN'DA YEREL VE GÜVENİLİR HİZMET",
  homeHeroTitle: "Servet İnşaat\nEmlak & Rent A Car",
  homeHeroText: "Gayrimenkul, inşaat ve araç kiralama ihtiyaçlarınız için doğrudan, şeffaf ve hızlı çözümler.",
  homeListingsButton: "İlanları İncele",
  homeCallButton: "Hemen Ara",
  servicesEyebrow: "HİZMETLERİMİZ",
  servicesTitle: "Tek çatı altında\nüç güçlü hizmet",
  servicesText: "İhtiyacınız ne olursa olsun, deneyim ve güvenle yanınızdayız.",
  realEstateTitle: "Emlak Danışmanlığı",
  realEstateText: "Satılık ve kiralık konut, arsa ve iş yeri seçenekleri.",
  constructionTitle: "İnşaat Projeleri",
  constructionText: "Planlamadan anahtar teslimine güvenilir yapı çözümleri.",
  rentalServiceTitle: "Rent A Car",
  rentalServiceText: "Bakımlı, konforlu ve ihtiyacınıza uygun kiralık araçlar.",
  projectsTitle: "Sağlam temeller,\ndeğerli yaşamlar",
  projectsText: "Kaliteli malzeme, titiz işçilik ve zamanında teslim prensibiyle çalışıyoruz.",
  aboutTitle: "Karaman'da işinize değer katan güvenilir çözüm ortağı",
  aboutText: "Servet İnşaat Emlak Rent A Car olarak gayrimenkul, yapı ve araç kiralama ihtiyaçlarınızda dürüst, hızlı ve çözüm odaklı hizmet sunuyoruz.",
  contactTitle: "Eviniz, projeniz veya aracınız için hemen iletişime geçin.",
  listingHeroEyebrow: "SERVET PORTFÖY",
  listingHeroTitle: "Güncel İlanlar",
  listingHeroText: "Satılık ve kiralık emlak seçeneklerimizi inceleyin.",
  rentalHeroEyebrow: "SERVET RENT A CAR · KARAMAN",
  rentalHeroTitle: "Aracınız hazır,\nyolculuğunuz başlasın.",
  rentalHeroText: "Araçlarımızı günlük, haftalık ve aylık kiralayabilirsiniz. Müsait araçlarımızı inceleyin, telefon veya WhatsApp ile bize ulaşın.",
  rentalHeroButton: "Boştaki araçları gör",
  rentalAvailableEyebrow: "HEMEN KİRALAYABİLİRSİNİZ",
  rentalAvailableTitle: "ŞU AN BOŞTAKİ ARAÇLARIMIZ",
  rentalAvailableText: "İhtiyacınıza uygun aracı seçin; günlük, haftalık veya aylık kiralama için bize ulaşın.",
  rentalCardNote: "Bu aracı günlük, haftalık veya aylık olarak kiralayabilirsiniz.",
  rentalDetailLink: "Araç detaylarını incele",
  rentalRentedEyebrow: "FİLODAKİ DİĞER ARAÇLAR",
  rentalRentedTitle: "Şu an kirada olanlar",
  rentalRentedText: "Bu araçlar yeniden müsait olduğunda bilgi almak için bizi arayabilirsiniz.",
} as const;

export type SiteContentKey = keyof typeof defaultSiteContent;
export type SiteContent = Record<SiteContentKey, string>;

export const siteContentFields: Array<{ group: string; key: SiteContentKey; label: string; multiline?: boolean }> = [
  { group: "Genel", key: "topLine", label: "Üst bilgi yazısı" },
  { group: "Genel", key: "brandSubtitle", label: "Logo alt yazısı" },
  { group: "Menü", key: "navHome", label: "Ana sayfa bağlantısı" },
  { group: "Menü", key: "navConstruction", label: "İnşaat bağlantısı" },
  { group: "Menü", key: "navRealEstate", label: "Emlak bağlantısı" },
  { group: "Menü", key: "navRental", label: "Araç kiralama bağlantısı" },
  { group: "Menü", key: "navAbout", label: "Hakkımızda bağlantısı" },
  { group: "Menü", key: "navContact", label: "İletişim bağlantısı" },
  { group: "Alt Bilgi", key: "footerDescription", label: "Firma açıklaması", multiline: true },
  { group: "Alt Bilgi", key: "footerAddress", label: "Adres", multiline: true },
  { group: "Alt Bilgi", key: "footerCopyright", label: "Telif yazısı" },
  { group: "Ana Sayfa", key: "homeHeroEyebrow", label: "Karşılama üst başlığı" },
  { group: "Ana Sayfa", key: "homeHeroTitle", label: "Karşılama başlığı", multiline: true },
  { group: "Ana Sayfa", key: "homeHeroText", label: "Karşılama açıklaması", multiline: true },
  { group: "Ana Sayfa", key: "homeListingsButton", label: "İlan butonu" },
  { group: "Ana Sayfa", key: "homeCallButton", label: "Arama butonu" },
  { group: "Hizmetler", key: "servicesEyebrow", label: "Hizmetler üst başlığı" },
  { group: "Hizmetler", key: "servicesTitle", label: "Hizmetler başlığı", multiline: true },
  { group: "Hizmetler", key: "servicesText", label: "Hizmetler açıklaması", multiline: true },
  { group: "Hizmetler", key: "realEstateTitle", label: "Emlak başlığı" },
  { group: "Hizmetler", key: "realEstateText", label: "Emlak açıklaması", multiline: true },
  { group: "Hizmetler", key: "constructionTitle", label: "İnşaat başlığı" },
  { group: "Hizmetler", key: "constructionText", label: "İnşaat açıklaması", multiline: true },
  { group: "Hizmetler", key: "rentalServiceTitle", label: "Araç kiralama başlığı" },
  { group: "Hizmetler", key: "rentalServiceText", label: "Araç kiralama açıklaması", multiline: true },
  { group: "Ana Sayfa", key: "projectsTitle", label: "Projeler başlığı", multiline: true },
  { group: "Ana Sayfa", key: "projectsText", label: "Projeler açıklaması", multiline: true },
  { group: "Ana Sayfa", key: "aboutTitle", label: "Hakkımızda başlığı", multiline: true },
  { group: "Ana Sayfa", key: "aboutText", label: "Hakkımızda açıklaması", multiline: true },
  { group: "Ana Sayfa", key: "contactTitle", label: "İletişim çağrısı", multiline: true },
  { group: "Emlak", key: "listingHeroEyebrow", label: "Sayfa üst başlığı" },
  { group: "Emlak", key: "listingHeroTitle", label: "Sayfa başlığı" },
  { group: "Emlak", key: "listingHeroText", label: "Sayfa açıklaması", multiline: true },
  { group: "Araç Kiralama", key: "rentalHeroEyebrow", label: "Karşılama üst başlığı" },
  { group: "Araç Kiralama", key: "rentalHeroTitle", label: "Karşılama başlığı", multiline: true },
  { group: "Araç Kiralama", key: "rentalHeroText", label: "Karşılama açıklaması", multiline: true },
  { group: "Araç Kiralama", key: "rentalHeroButton", label: "Karşılama butonu" },
  { group: "Araç Kiralama", key: "rentalAvailableEyebrow", label: "Müsait araçlar üst başlığı" },
  { group: "Araç Kiralama", key: "rentalAvailableTitle", label: "Müsait araçlar başlığı" },
  { group: "Araç Kiralama", key: "rentalAvailableText", label: "Müsait araçlar açıklaması", multiline: true },
  { group: "Araç Kiralama", key: "rentalCardNote", label: "Araç kartı açıklaması", multiline: true },
  { group: "Araç Kiralama", key: "rentalDetailLink", label: "Detay bağlantısı" },
  { group: "Araç Kiralama", key: "rentalRentedEyebrow", label: "Kiradaki araçlar üst başlığı" },
  { group: "Araç Kiralama", key: "rentalRentedTitle", label: "Kiradaki araçlar başlığı" },
  { group: "Araç Kiralama", key: "rentalRentedText", label: "Kiradaki araçlar açıklaması", multiline: true },
];

export async function getSiteContent(): Promise<SiteContent> {
  const snapshot = await adminDb.collection("settings").doc("site-content").get();
  const stored = snapshot.exists ? snapshot.data() : {};
  return Object.fromEntries(Object.entries(defaultSiteContent).map(([key, fallback]) => [key, typeof stored?.[key] === "string" && stored[key].trim() ? stored[key] : fallback])) as SiteContent;
}
